library(BioNAR)
library(testthat)
test_that("proper treatment of singletones",{
    sg<-graph_from_literal(A)
    cl<-getClustering(sg,'lec')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"leading eigenvector")
    cl<-getClustering(sg,'wt')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"walktrap")
    cl<-getClustering(sg,'fc')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"fast greedy")
    cl<-getClustering(sg,'infomap')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"infomap")
    cl<-getClustering(sg,'louvain')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"multi level")
    cl<-getClustering(sg,'sgG1')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,"spinglass")
    cl<-getClustering(sg,'spectral')
    expect_equal(cl$membership,c(1))
    expect_equal(cl$algorithm,'spectral')
})
